#!/bin/bash

psql -U ${POSTGRES_USER} -d ${POSTGRES_DB} <<-END

CREATE ROLE "${POSTGRES_USER_READER}" WITH LOGIN PASSWORD '${POSTGRES_USER_READER}' NOSUPERUSER INHERIT NOCREATEDB NOCREATEROLE NOREPLICATION;

GRANT
SELECT
  ON ALL TABLES IN SCHEMA public TO ${POSTGRES_USER_READER};

CREATE ROLE "${POSTGRES_USER_SECURE}" WITH LOGIN PASSWORD '${POSTGRES_PASSWORD_SECURE}' NOSUPERUSER INHERIT NOCREATEDB NOCREATEROLE NOREPLICATION;

GRANT
SELECT, UPDATE, DELETE
    ON ALL TABLES IN SCHEMA public TO ${POSTGRES_USER_SECURE};
END