version: "3.9"

services:
  postgres:
    container_name: postgres
    image: postgres:latest
    restart: on-failure
    ports:
      - 5432:5432
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD_FILE: /run/secrets/pg_admin_password
    command:
      [
        "postgres",
        "-c",
        "ssl=on",
        "-c",
        "ssl_cert_file=/var/lib/postgresql/certs/cert.pem",
        "-c",
        "ssl_key_file=/var/lib/postgresql/certs/private.pem",
      ]
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "sh -c 'pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}'",
        ]
      interval: 10s
      timeout: 3s
      retries: 3
    volumes:
      - ./init:/docker-entrypoint-initdb.d:ro
      - ./certs/:/var/lib/postgresql/certs/:ro #chmod 400 private.pem on local
    secrets:
      - pg_admin_password

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin4
    depends_on:
      - postgres
    restart: always
    ports:
      - 5555:80
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD_FILE: /run/secrets/pg_admin_password
    secrets:
      - pg_admin_password

secrets:
  pg_admin_password:
    file: secrets/pg_admin_password.txt
