namespace: vault-tt
global:
  enabled: true
  tlsDisable: true

injector:
  enabled: false

server:
  affinity: ""

  volumeMounts:
    - name: vault-tt-setup
      mountPath: /vault/scripts
  volumes:
    - name: vault-tt-setup
      configMap:
        name: vault-tt-setup
        defaultMode: 0777
        items:
          - key: init.sh
            path: init.sh

  postStart:
    - /bin/sh
    - -c
    - /vault/scripts/init.sh

  ha:
    replicas: 2
    enabled: true
    raft:
      enabled: true
      setNodeId: true
      config: |
        ui = true
        cluster_name = "vault-tt-raft"

        listener "tcp" {
           address = "[::]:8200"
           cluster_address = "[::]:8201"
           tls_disable = "true"
        }

        storage "raft" {
          path    = "/vault/data/"
          tls_skip_verify = "true" 
          retry_join {
              leader_api_addr = "http://vault-tt-0.vault-tt-internal:8200"
            }
          retry_join {
              leader_api_addr = "http://vault-tt-1.vault-tt-internal:8200"
            }
        }

        service_registration "kubernetes" {}
