global:
  enabled: true
  tlsDisable: false

injector:
  enabled: true

server:
  extraEnvironmentVars:
    VAULT_CACERT: /vault/certs/vault.ca
    VAULT_TLSCERT: /vault/certs/vault.crt
    VAULT_TLSKEY: /vault/certs/vault.key

  affinity: ""

  volumeMounts:
    - name: vault-ha-tls
      mountPath: /vault/certs
      readOnly: true
    - name: vault-setup
      mountPath: /vault/scripts

  volumes:
    - name: vault-ha-tls
      secret:
        defaultMode: 420
        secretName: vault-ha-tls
    - name: vault-setup
      configMap:
        name: vault-setup
        defaultMode: 0777
        items:
          - key: vault.sh
            path: vault.sh

  readinessProbe:
    enabled: true
    path: "/v1/sys/health?standbyok=true&sealedcode=204&uninitcode=204"

  postStart:
    - /bin/sh
    - -c
    - echo "START INIT SCRIPT"
    - -c
    - /vault/scripts/vault.sh

  standalone:
    enabled: false

  ha:
    replicas: 2
    enabled: true
    raft:
      enabled: true
      setNodeId: true
      config: |
        ui = 1
        cluster_name = "vault-integrated-storage"

        listener "tcp" {
           tls_disable = 0
           address = "[::]:8200"
           cluster_address = "[::]:8201"
           tls_cert_file = "/vault/certs/vault.crt"
           tls_key_file  = "/vault/certs/vault.key"
           tls_client_ca_file = "/vault/certs/vault.ca"
        }

        storage "raft" {
          path    = "/vault/data/"
          retry_join {
              leader_api_addr = "https://vault-0.vault-internal:8200"
              leader_client_cert_file = "/vault/certs/vault.crt"
              leader_client_key_file  = "/vault/certs/vault.key"
              leader_ca_cert_file = "/vault/certs/vault.ca"            
            }
          retry_join {
              leader_api_addr = "https://vault-1.vault-internal:8200"
              leader_client_cert_file = "/vault/certs/vault.crt"
              leader_client_key_file  = "/vault/certs/vault.key"
              leader_ca_cert_file = "/vault/certs/vault.ca" 
            }
        }

        seal "transit" {
          address = "http://vault-tt.vault-tt:8200"
          token = ""
          disable_renewal = 0
          key_name = "autounseal"
          mount_path = "transit/"
          tls_skip_verify = 1
        }

        service_registration "kubernetes" {}

ui:
  enabled: true
  publishNotReadyAddresses: true
  activeVaultPodOnly: true
  serviceType: "LoadBalancer"
  serviceNodePort: null
  externalPort: 8200
  targetPort: 8200
